version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - auth
      - postgres
      - redis
    volumes:
      - ./gateway/:/go/src/app

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ./auth/:/go/src/app

  user:
    container_name: user
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    volumes:
      - ./auth/:/go/src/app

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ""

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
