version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - auth
    volumes:
      - ./gateway/:/go/src/app

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ./auth/:/go/src/app
